"""创建用户任务标签及任务标签关联表

Revision ID: ea1eaf00d47f
Revises: 02af0f92c4cd
Create Date: 2026-08-25 21:51:25.202944

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# Alembic 使用以下标识构建迁移版本链；生成后不要随意修改 revision。
revision: str = "ea1eaf00d47f"
down_revision: str | Sequence[str] | None = "02af0f92c4cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """按当前版本定义升级数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="标签主键"),
        sa.Column("name", sa.String(length=50), nullable=False, comment="标签名称"),
        sa.Column("color", sa.String(length=7), nullable=True, comment="标签显示颜色"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tag")),
        comment="标签信息表",
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(op.f("ix_tag_name"), "tag", ["name"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="用户主键"),
        sa.Column("username", sa.String(length=50), nullable=False, comment="用户登录名"),
        sa.Column("email", sa.String(length=255), nullable=False, comment="用户邮箱地址"),
        sa.Column(
            "password_hash", sa.String(length=255), nullable=False, comment="Argon2 密码哈希"
        ),
        sa.Column(
            "role",
            sa.String(length=30),
            server_default=sa.text("'user'"),
            nullable=False,
            comment="用户角色",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("1"),
            nullable=False,
            comment="账号是否启用",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        comment="用户信息表",
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "task",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="任务主键"),
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="所属用户主键"),
        sa.Column("title", sa.String(length=200), nullable=False, comment="任务标题"),
        sa.Column("description", sa.Text(), nullable=True, comment="任务详细说明"),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'pending'"),
            nullable=False,
            comment="任务状态",
        ),
        sa.Column(
            "priority",
            sa.SmallInteger(),
            server_default=sa.text("3"),
            nullable=False,
            comment="任务优先级（1-5）",
        ),
        sa.Column("due_date", sa.DateTime(), nullable=True, comment="任务截止时间"),
        sa.Column("completed_at", sa.DateTime(), nullable=True, comment="任务完成时间"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'in_progress', 'completed', 'cancelled')",
            name=op.f("ck_task_valid_status"),
        ),
        sa.CheckConstraint("priority BETWEEN 1 AND 5", name=op.f("ck_task_valid_priority")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_task_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task")),
        comment="任务信息表",
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index("ix_task_due_date", "task", ["due_date"], unique=False)
    op.create_index(op.f("ix_task_user_id"), "task", ["user_id"], unique=False)
    op.create_index("ix_task_user_status", "task", ["user_id", "status"], unique=False)
    op.create_table(
        "task_tag",
        sa.Column("task_id", sa.BigInteger(), nullable=False, comment="任务主键"),
        sa.Column("tag_id", sa.BigInteger(), nullable=False, comment="标签主键"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="关联创建时间",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tag.id"], name=op.f("fk_task_tag_tag_id_tag"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name=op.f("fk_task_tag_task_id_task"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("task_id", "tag_id", name=op.f("pk_task_tag")),
        comment="任务与标签关联表",
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(op.f("ix_task_tag_tag_id"), "task_tag", ["tag_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """撤销 upgrade 中的结构变化。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_tag_tag_id"), table_name="task_tag")
    op.drop_table("task_tag")
    op.drop_index("ix_task_user_status", table_name="task")
    op.drop_index(op.f("ix_task_user_id"), table_name="task")
    op.drop_index("ix_task_due_date", table_name="task")
    op.drop_table("task")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_tag_name"), table_name="tag")
    op.drop_table("tag")
    # ### end Alembic commands ###
